#! /usr/bin/perl
use strict;
use warnings;

my $file = $ARGV[0];

system "perl -wnlpi -e 's/^\\s+//g' $file";

system "perl -wnlpi -e 's/\\s+/,/g' $file";

system "perl -i -pe 's/(#eig).*/name,x,y,z,xx,yy,zz,group/' $file"
